### ISSUE TITLE
database need an API for the map

### ISSUE THREAD

**Issue by jojorb** [hakkens/precious-plastic-map#1]
please details here the needs for this API

**Comment by eliottvincent** [comment]
Quick thoughts:

We first have to install a plugin on the wordpress side. Here are the possibilities:
[JSON-API plugin](https://fr.wordpress.org/plugins/json-api/
)
[WP REST API](http://v2.wp-api.org/)
I haven't looked further for the moment, will do it tomorrow.

Once we've installed the plugin, we have to check GET and PUT requests, once they'll be working we'll be good

**Comment by sabatesduran** [comment]
@eliottvct I've used WP REST API before and it was good, never tried JSON-API.

**Comment by semeano** [comment]
Same here. BTW, what are the differences?

**Comment by eliottvincent** [comment]
I never used this kind of plugin, just wanted to give us the choice 😉
But if you two have already used WP REST API we should go to this one

**Comment by eliottvincent** [comment]
@semeano I haven't checked the differences but I guess they are minimal

**Comment by alromh87** [comment]
Since WP REST API is included in WP since 4.7 I think we should stick with it
![rest](https://cloud.githubusercontent.com/assets/7505980/24739125/03c30d82-1a60-11e7-8979-3243ca49479d.png)

**Comment by alromh87** [comment]
Basic implementation using WP REST API has been published at:
alromh87/davehakkens@360f72f1ef0b66e59dbc2c13e4536947f9e6ee49
At the moment Pins can be registered and shown in the map from WP, available services and hashtags are stored at WP as Taxonomy and loaded from the map at runtime, so they can be easily extended if needed.

Basic map displaying:
alromh87/precious-plastic-map@d3c39abc851a3cf4352df20c82ceccce6a5ca7bc

I will start working with  users adding pins.

**Comment by alromh87** [comment]
I have implemented pin storage as custom posts in wordpress, even doe this creates many GUI components to interact with data we won't get the best performance out of it, so I will start building custom DB and services on top of WP.
@nandocraft @davehakkens @RobyRemzy

**Comment by alromh87** [comment]
And it turns out, it was pretty easy, will get good news soon!!

**Comment by alromh87** [comment]
Now using custom DB trough WP REST API, for better performance and independence, now it is possible to create pins from REST API also started working on GUI integration for logIn and pin creation.
alromh87/precious-plastic-map@da80f6035383840a984e88d38ab7784a62968b18
alromh87/davehakkens/commit/63ca74fb7f8e455cbe55696a14edfd01c668627e

**Comment by alromh87** [comment]
I have enabled authentication, so we are getting close, I cloned official site DB so registered users can create pins @ test site. Please give it a try, right now you input an address and select one of the options in order to get lat lng.
