### ISSUE TITLE
set up the dev environment for the Wordpress and the README.md on how to setup it

### ISSUE THREAD

**Issue by jojorb** [hakkens/precious-plastic-map#11]
This task will be provided by alromh87

**Comment by alromh87** [comment]
Work is being uploaded to temporal github repo:
https://github.com/alromh87/testPPInstall

**Comment by jojorb** [comment]
great info m8, thanks for that. So hopefully here there is no need to fire composer, right?

**Comment by alromh87** [comment]
I haven't used composer, but I think in this scenario it is not needed, everything gets installed and ready for dev, with those instructions
